### ISSUE TITLE
TF XML Ingest

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mt_metadata#143]
During the course of work on issue [252](https://github.com/simpeg/aurora/issues/252) in aurora some errors were encountered handling XML data from SPUD.

XML TFs were downloaded from SPUD and subsequently attempted to load into mt_metdata using the syntax.
```
from mt_metadata.transfer_functions.core import TF
spud_tf = TF(file_path)
spud_tf.read_tf_file()
```

The downloading of the SPUD XML was done in April 2023 using the script: `catalog_SPUD.py`
on the `earthscope_tests` branch of `aurora`.  The file is in `aurora/aurora/test_utils/earthscope/`

The result of running this is an archive of local xml files for testing, and a summary csv called "spud_summary.csv"
[spud_summary.csv](https://github.com/kujaku11/mt_metadata/files/11578539/spud_summary.csv)

There were two primary sources for these files:

EMTF_URL = "https://ds.iris.edu/spudservice/emtf"
DATA_URL = "https://ds.iris.edu/spudservice/data"

Ongoing work on issue 252 is using the DATA_URL files.

Iterating over these files resulted in the following results to the read_tf_file() command:

All files from the EMTF_URL encounter the same KeyError with message "field_notes"

Here is a snippet from interactive session:
```
tf = load_xml_tf(df.emtf_xml_path.iloc[0])
No external_url in EMTF XML
No primary_data in EMTF XML
No attachment in EMTF XML
No provenance in EMTF XML
No copyright in EMTF XML
No site in EMTF XML
Traceback (most recent call last):
  File "/home/kkappler/anaconda3/envs/aurora/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-14-e6d171691b89>", line 1, in <module>
    tf = load_xml_tf(df.emtf_xml_path.iloc[0])
  File "<ipython-input-13-61506717b967>", line 8, in load_xml_tf
    spud_tf.read_tf_file()
  File "/home/kkappler/software/irismt/mt_metadata/mt_metadata/transfer_functions/core.py", line 1259, in read_tf_file
    tf_obj = read_file(self.fn, file_type=file_type, **kwargs)
  File "/home/kkappler/software/irismt/mt_metadata/mt_metadata/transfer_functions/io/readwrite.py", line 178, in read_file
    return file_reader(fn, **kwargs)
  File "/home/kkappler/software/irismt/mt_metadata/mt_metadata/transfer_functions/io/emtfxml/emtfxml.py", line 1144, in read_emtfxml
    obj.read(fn)
  File "/home/kkappler/software/irismt/mt_metadata/mt_metadata/transfer_functions/io/emtfxml/emtfxml.py", line 330, in read
    self._reader_dict[element](root_dict)
  File "/home/kkappler/software/irismt/mt_metadata/mt_metadata/transfer_functions/io/emtfxml/emtfxml.py", line 545, in _read_field_notes
    if not isinstance(root_dict["field_notes"], list):
KeyError: 'field_notes'
```
That occurred trying to read a file with content from this [example xml](https://ds.iris.edu/spudservice/emtf/13597847)
__________________________________________
__________________________________________

Regarding the DATA_URL files, of 7156 total TF xml files identified during the SPUD scraping process, trying to read these in yielded the following stats:
5373 of the files failed on read-in
1783 loaded successfully

There were four flavours of error:

3238 of the 5373 errors were `KeyError: 'field_notes'` as above

4 of the 5373  errors were `KeyError:` `value' 
Here an an [example xml](https://ds.iris.edu/spudservice/data/15032768)

780 of the 5373 errors were `AttributeError:` with message `"'list' object has no attribute 'items'"
Here an an [example xml](https://ds.iris.edu/spudservice/data/16175752)

And finally, 1351 errors were: `MTSchemaError:`
These split into 1191 with error message:
"Paper Citation Required not found in options list ['unrestricted release', 'restricted release']"
Here an an [example xml](https://ds.iris.edu/spudservice/data/15628718)
and 160 with error message:
"Academic Use Only not found in options list ['unrestricted release', 'restricted release']"
Here an an [example xml](https://ds.iris.edu/spudservice/data/16275436)

For the record, here is an output from a reading operation over all files from 26 May 2023
[spud_xml_review_2023-05-26_09:51:58.csv](https://github.com/kujaku11/mt_metadata/files/11578690/spud_xml_review_2023-05-26_09.51.58.csv)

**Comment by kkappler** [comment]
@kujaku11 After yesterdays updates to the `fcs` branch of mt_metadata the following stats are compiled:

**EMTF_URL Files:**

750 Load Successfully
6406 Errors
(Previous 0 Load Successfully and 7156 Errors)

All were `KeyError:` with message: `site`

> load_xml_tf(df.emtf_xml_path.iloc[751])
reading /home/kkappler/.cache/earthscope/spud_xml/emtf/15027669.xml
No external_url in EMTF XML
No primary_data in EMTF XML
No attachment in EMTF XML
No provenance in EMTF XML
No copyright in EMTF XML
Traceback (most recent call last):
  File "/home/kkappler/anaconda3/envs/aurora/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-21-e9f6f0cd6457>", line 1, in <module>
    qq = load_xml_tf(df.emtf_xml_path.iloc[751])
  File "/home/kkappler/software/irismt/aurora/tests/earthscope/test_load_spud_tfs.py", line 63, in load_xml_tf
    spud_tf.read()
  File "/home/kkappler/software/irismt/mt_metadata/mt_metadata/transfer_functions/core.py", line 1392, in read
    self._read_write_dict[file_type]["read"](self.fn, **kwargs)
  File "/home/kkappler/software/irismt/mt_metadata/mt_metadata/transfer_functions/core.py", line 1585, in from_emtfxml
    emtfxml_obj.read(self._fn)
  File "/home/kkappler/software/irismt/mt_metadata/mt_metadata/transfer_functions/io/emtfxml/emtfxml.py", line 302, in read
    attr.read_dict(root_dict)
  File "/home/kkappler/software/irismt/mt_metadata/mt_metadata/transfer_functions/io/emtfxml/metadata/site.py", line 104, in read_dict
    for element in input_dict["site"].keys():
KeyError: 'site'

Here is an [example url](http://ds.iris.edu/spudservice/emtf/15027669) for one that encountered this error. 

________________________________
________________________________
________________________________


**DATA_URL Files:**

2614 Load Successfully
4542 Errors
(Previous 1783 Load Successfully and 5373 Errors)

The breakdown of these was
`AttributeError`    2429
`MTSchemaError`     1832
`KeyError`           164
`ValueError`         117


For the `AttributeError` case there were three distinct errors encountered:

1. 'str' object has no attribute 'author'               2267
[example xml](https://ds.iris.edu/spudservice/data/15044964)

2. 'NoneType' object has no attribute 'component'        115
[example xml](https://ds.iris.edu/spudservice/data/16094133)

3. 'FieldNotes' object has no attribute 'instrument'      47
[example xml](https://ds.iris.edu/spudservice/data/16687273)


For the `MTSchemaError` case there were four distinct errors encountered:

1. Paper Citation Required not found in options list ['Unrestricted release', 'Restricted release']                                    1349
[example xml](https://ds.iris.edu/spudservice/data/18209395)

2. derived data type not found in options list ['error estimate', 'signal coherence', 'signal power estimate', 'primary data type']     210
[example xml](https://ds.iris.edu/spudservice/data/15605193)

3. Academic Use Only not found in options list ['Unrestricted release', 'Restricted release']                                           172
[example xml](https://ds.iris.edu/spudservice/data/16275436)

4. Conditions Apply not found in options list ['Unrestricted release', 'Restricted release']                                            101
[example xml](https://ds.iris.edu/spudservice/data/16233180)

For the `KeyError` case there was only one errors message: `value`:          164
[example xml](https://ds.iris.edu/spudservice/data/16705685)


For the `ValueError` case there were eight distinct subcases, but they were all associated with datetime parsing         117
1. Could not parse 2003-14-09 into a readable date-time             77
[example xml](https://ds.iris.edu/spudservice/data/15600189)

2. Could not parse 1996-29-02 into a readable date-time             10
[example xml](https://ds.iris.edu/spudservice/data/15368532)

3. Could not parse 2008-13-08T00:00:00 into a readable date-time     9
[example xml](https://ds.iris.edu/spudservice/data/16177700)

4. Could not parse 2008-17-08T00:00:00 into a readable date-time     7
[example xml](https://ds.iris.edu/spudservice/data/16179919)

5. Could not parse 2008-15-08T00:00:00 into a readable date-time     6
[example xml](https://ds.iris.edu/spudservice/data/16180248)

6. Could not parse 2008-16-08T00:00:00 into a readable date-time     4
[example xml](https://ds.iris.edu/spudservice/data/16176516)

7. Could not parse 2009-14-09T00:00:00 into a readable date-time     3
[example xml](https://ds.iris.edu/spudservice/data/16179352)

8. Could not parse 2010-17-08T00:00:00 into a readable date-time     1
[example xml](https://ds.iris.edu/spudservice/data/16179796)

**Comment by kkappler** [comment]
@kujaku11 Pulled latest mth5 and mt_metadata and re-ran the xml ingest:
`AttributeError`  dropped from 2429 to 56.  Great progress!

All 56 remaining error messages were of the form:

> "FieldNotes object has no attribute 'instrument'"

No other changes observed.

**Comment by kujaku11** [comment]
@kkappler Try re-running the xml ingest after pulling fcs branch.  I think I fixed all the bugs?

**Comment by kkappler** [comment]
@kujaku11 Very close!
Only 3 exceptions and 7153 successful ingests.

The remaining errors were all the same:
`ValueError`
`Could not parse string 2011-12-31T24:00:00 check formatting, should be YYYY-MM-DDThh:mm:ss.ns`

Here is a [sample file](https://ds.iris.edu/spudservice/data/16175752)

(The emtf_xml are still not reading in though )

**Comment by kujaku11** [comment]
@kkappler Nice!

I'm not sure if the `ValueError` should be handled at this point, but maybe in the future? Need a decent amount of logic to parse that time format.  

When you say emtf_xml are still not reading is it the same `KeyError: site` error?  When I read in the example file from the emtf_url above it reads in fine.  Is there another error?

**Comment by kkappler** [comment]
@kujaku11 I didn't see the above comment in time, but good that it is here for posterity.  
Instead, I modified the `curl` command adding the option: `-H 'Accept: application/xml'` and rescraped the emtf files.  

Here is the summary:

**EMTF**
7153/7156 read in successfully
3/7156 have error:
`KeyError(Comments)`
The offending XML IDs are: [13597847, 13597976, 13598200], the first of which can be accessed [here](https://ds.iris.edu/spudservice/emtf/13597847).
99.96% of the way there:)

**DATA**
7152/7156 read in successfully
4/7156 have errors.
3 of these 4 errors are the UTC Midnight timestamp referenced previously, and FWIW, these are the exact same three files that fail for EMTF, so you can use the link above in this post (its for KAK observatory in Japan).
The final error is new since I updated mt_metadata, it is `ParseError(no element found: line 253, column 38)`
and is associated with this [link](https://ds.iris.edu/spudservice/data/13650297).
99.94% of the way there:)

**Comment by kkappler** [comment]
These are now all reading in, 7156 emtf and data sourced tf xml

**Comment by kkappler** [comment]
@kujaku11 Using the latest updates to mt_metadata fcs branch we get the summary below 

> Took 720s to review spud tfs
data error 
 False    6376
True      780
emtf error 
 False    6376
True      780

Every error was identical  `AttributeError, 'list' object has no attribute 'items'`
There was a 1:1 correspondence between data and emtf versions of the TFs, i.e. the emtf version reads in IFF the data version did.
 
Here is an emtf [link](https://ds.iris.edu/spudservice/emtf/13597847)
and a data [link](https://ds.iris.edu/spudservice/data/16175752) 
corresponding to the first row of the output table
[01_spud_xml_review_2023-08-19_121922.csv](https://github.com/kujaku11/mt_metadata/files/12386867/01_spud_xml_review_2023-08-19_121922.csv)

**Comment by kujaku11** [comment]
@kkappler Updated `mt_metadata.transfer_function.io.emtfxml.metadata.Attachment` to handle multiple attachments in commit [a41ccb6](https://github.com/kujaku11/mt_metadata/pull/142/commits/a41ccb6227a1feee3c3c7e7406fa7e52ed0769eb).  See if that works.

**Comment by kkappler** [comment]
@kujaku11 your fix worked on the xml of "emtf" type, but not on the corresponding one of "data" type.

> element_dict["attachment"]
Out[1]: 
[OrderedDict([('filename', 'kak/kak.mtres.all.1r1.rp')]),
 OrderedDict([('filename', 'kak/kak.mtres.all.1r2.rp')]),
 OrderedDict([('filename', 'kak/kak.mtres.all.2r1.rp')]),
 OrderedDict([('filename', 'kak/kak.mtres.all.2r2.rp')])]
>

**Comment by kkappler** [comment]
Took 740.s to review spud tfs, running with 1 partitions
.cache/earthscope/summary_tables/01_spud_xml_review_2023-08-22_141418.csv
data error 
 False    7156

emtf error 
 False    7156
